const mongoose = require("mongoose");
const dotenv = require("dotenv"); 
const Product = require("./src/models/Product");
const connectDB = require("./src/config/db");

dotenv.config(); // .env dosyasını yüklemek için

const products = [
  {
    name: "Beyaz Tişört",
    gender: "Erkek",
    category: "Üst Giyim",
    subCategory: "Tişört",
    price: 279.99,
    size: ["M", "L", "XL", "XXL"],
    color: ["Beyaz"],
    material: "Pamuk",
    length: "Kısa",
    stock: 60,
    description: "Nefes alabilir kumaştan üretilmiş basic beyaz tişört.",
    features: ["Yüksek dayanıklılık", "Yumuşak dokulu kumaş"],
    tags: ["basic", "günlük", "erkek"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Turkuaz O Yaka Kısa Kollu Tişört",
    gender: "Erkek",
    category: "Üst Giyim",
    subCategory: "Tişört",
    price: 319.99,
    size: ["M", "L", "XL"],
    color: ["Turkuaz"],
    material: "Pamuk",
    length: "Kısa",
    stock: 45,
    description: "Canlı renkli, rahat kesim turkuaz tişört.",
    features: ["Rahat kalıp", "Nefes alabilir kumaş"],
    tags: ["renkli", "erkek", "günlük"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Gri Tişört",
    gender: "Erkek",
    category: "Üst Giyim",
    subCategory: "Tişört",
    price: 299.99,
    size: ["S", "M", "L"],
    color: ["Gri"],
    material: "Pamuk",
    length: "Kısa",
    stock: 50,
    description: "Günlük kullanıma uygun gri basic tişört.",
    features: ["Kolay ütülenebilir", "Yumuşak doku"],
    tags: ["basic", "erkek"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Bej Bluz",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Bluz",
    price: 549.99,
    size: ["36", "38", "40"],
    color: ["Bej"],
    material: "İpek",
    length: "Orta",
    stock: 30,
    description: "Zarif ve sade bej renkte ipek bluz.",
    features: ["Yumuşak kumaş", "Klasik kesim"],
    tags: ["bluz", "kadın", "şık"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Mavi Polo Yaka Kısa Kollu Tişört",
    gender: "Erkek",
    category: "Üst Giyim",
    subCategory: "Tişört",
    price: 389.99,
    size: ["M", "L", "XL"],
    color: ["Mavi"],
    material: "Pamuk",
    length: "Kısa",
    stock: 35,
    description: "Klasik kesim, polo yaka mavi tişört.",
    features: ["Hava geçirgen kumaş", "Esnek yapı"],
    tags: ["polo", "erkek", "günlük"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Kahve Uzun Kollu Elbise",
    gender: "Kadın",
    category: "Elbise",
    subCategory: "Uzun Elbise",
    price: 1999.99,
    size: ["36", "38", "40"],
    color: ["Kahve"],
    material: "Yün karışımlı kumaş",
    length: "Uzun",
    stock: 20,
    description: "Şık ve zarif kahverengi uzun kollu elbise.",
    features: ["Yumuşak kumaş", "Modern tasarım"],
    tags: ["kadın", "şık", "uzun"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Yeşil Deri Mont",
    gender: "Kadın",
    category: "Dış Giyim",
    subCategory: "Mont",
    price: 2799.99,
    size: ["36", "38", "40"],
    color: ["Yeşil"],
    material: "Hakiki Deri",
    length: "Orta",
    stock: 12,
    description: "Modern kesim yeşil hakiki deri mont.",
    features: ["Hakiki deri", "Dayanıklı astar"],
    tags: ["mont", "deri", "kadın"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Ecru Kolsuz Elbise",
    gender: "Kadın",
    category: "Elbise",
    subCategory: "Kısa Elbise",
    price: 1650.5,
    size: ["36", "38", "40"],
    color: ["Ekru"],
    material: "Keten",
    length: "Kısa",
    stock: 25,
    description: "Zarif kolsuz keten elbise, yaz ayları için ideal.",
    features: ["Nefes alabilir kumaş", "Yazlık kesim"],
    tags: ["elbise", "kadın", "yazlık"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Gri Uzun Kollu Elbise",
    gender: "Kadın",
    category: "Elbise",
    subCategory: "Uzun Elbise",
    price: 1799.9,
    size: ["36", "38", "40"],
    color: ["Gri"],
    material: "Viskon",
    length: "Uzun",
    stock: 22,
    description: "Gri tonlarında zarif ve sade uzun kollu elbise.",
    features: ["Şık görünüm", "Rahat kesim"],
    tags: ["kadın", "günlük", "uzun"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Siyah Süet Ayakkabı",
    gender: "Kadın",
    category: "Ayakkabı",
    subCategory: "Topuklu",
    price: 2150.99,
    size: ["36", "37", "38", "39"],
    color: ["Siyah"],
    material: "Süet",
    length: "Orta", 
    stock: 18,
    description: "Zarif tasarımlı siyah süet topuklu ayakkabı.",
    features: ["Hakiki süet", "Rahat taban"],
    tags: ["ayakkabı", "süet", "kadın"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    name: "Çift Pilili Ufak Ekose Flanel Pantolon",
    gender: "Erkek",
    category: "Alt Giyim", 
    subCategory: "Pantolon",
    price: 8990,
    size: ["46", "48", "50", "52"],
    color: ["Gri", "Ekose"],
    material: "Yün Karışımlı", 
    length: "Uzun", 
    stock: 12,
    description:
      "Yün karışımlı kumaştan üretilen bu pantolon, klasik ekose deseni ve çift pilili tasarımıyla sofistike bir görünüm sunar.",
    features: ["Çift Pilili", "Flanel Kumaş", "Vakko"], 
    tags: ["erkek", "pantolon", "ekose", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Bej Süet Bot",
    gender: "Kadın",
    category: "Ayakkabı", 
    subCategory: "Bot",
    price: 14990,
    size: ["37", "38", "39"], 
    color: ["Bej"], 
    material: "Süet", 
    length: "Orta", 
    stock: 8,
    description:
      "Yüksek kaliteli süet materyalden üretilmiş bu bej bot, zarif dikiş detaylarıyla şıklığı ve konforu bir arada sunar.",
    features: ["Yüksek kaliteli süet", "Zarif dikiş detayları", "Vakko"],
    tags: ["kadın", "bot", "süet", "bej", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Siyah Şort",
    gender: "Kadın",
    category: "Alt Giyim", 
    subCategory: "Şort",
    price: 5990,
    size: ["36", "38", "40"], 
    color: ["Siyah"], 
    material: "Kumaş", 
    length: "Kısa", 
    stock: 10,
    description:
      "Minimal tasarımı ve kaliteli kumaşıyla öne çıkan bu siyah şort, günlük ve şık kombinlerde tercih edilir.",
    features: ["Minimal tasarım", "Kaliteli kumaş", "Vakko"],
    tags: ["kadın", "şort", "siyah", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Yarım Balıkçı Yaka Yün Triko",
    gender: "Erkek",
    category: "Üst Giyim", 
    subCategory: "Triko",
    price: 7490,
    size: ["M", "L", "XL"],
    color: ["Bilinmiyor"], 
    material: "Yün", 
    length: "Orta", 
    stock: 14,
    description:
      "Saf yün içeriğiyle konforlu ve sıcak tutan bu triko, yarım balıkçı yaka detayıyla modern bir görünüm sunar.",
    features: ["Saf yün", "Yarım Balıkçı Yaka", "Vakko"],
    tags: ["erkek", "triko", "yün", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Bej Etek",
    gender: "Kadın",
    category: "Alt Giyim", 
    subCategory: "Etek",
    price: 7990,
    size: ["36", "38", "40"], 
    color: ["Bej"], 
    material: "Kumaş", 
    length: "Orta", 
    stock: 9,
    description:
      "Zarif kesimiyle dikkat çeken bu bej etek, klasik ve modern çizgileri bir arada taşır. Günlük veya ofis kombinleri için idealdir.",
    features: ["Zarif kesim", "Vakko"],
    tags: ["kadın", "etek", "bej", "vakko", "ofis"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Altın Renkli Küpe",
    gender: "Kadın",
    category: "Aksesuar", 
    subCategory: "Küpe",
    price: 3490,
    size: ["Tümü"], 
    color: ["Altın"], 
    material: "Metal", 
    length: "Kısa", 
    stock: 20,
    description:
      "Şık ve zarif tasarıma sahip bu altın tonlu küpe, her kombini tamamlayan zamansız bir aksesuardır.",
    features: ["Zarif tasarım", "Vakko"],
    tags: ["kadın", "küpe", "aksesuar", "altın", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Siyah Smokin Takım",
    gender: "Erkek",
    category: "Takım Elbise", 
    subCategory: "Smokin",
    price: 29990,
    size: ["48", "50", "52", "54"], 
    color: ["Siyah"], 
    material: "Kumaş", 
    length: "Uzun", 
    stock: 5,
    description:
      "Klasik siyah renkli bu smokin takım, özel davetlerde kusursuz bir şıklık sunar. Kaliteli kumaş yapısıyla konforludur.",
    features: ["Kaliteli kumaş", "Klasik kesim", "Vakko"],
    tags: ["erkek", "smokin", "siyah", "vakko", "davet"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Bej Bluz", 
    gender: "Kadın",
    category: "Üst Giyim", 
    subCategory: "Bluz",
    price: 6490,
    size: ["36", "38", "40"], 
    color: ["Bej"], 
    material: "Kumaş", 
    length: "Orta", 
    stock: 15,
    description:
      "Yumuşak dokulu kumaşıyla rahat bir kullanım sunan bu bej bluz, sade şıklığıyla öne çıkar.",
    features: ["Yumuşak doku", "Sade şıklık", "Vakko"],
    tags: ["kadın", "bluz", "bej", "vakko", "sade"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Yeşil Deri Mont", 
    gender: "Erkek", 
    category: "Dış Giyim", 
    subCategory: "Mont",
    price: 17990,
    size: ["M", "L", "XL"], 
    color: ["Yeşil"], 
    material: "Gerçek Deri", 
    length: "Orta", 
    stock: 6,
    description:
      "Gerçek deriden üretilmiş bu yeşil mont, modern kesimiyle güçlü bir duruş sergiler.",
    features: ["Gerçek Deri", "Modern kesim", "Vakko"],
    tags: ["erkek", "mont", "deri", "yeşil", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Kahve Uzun Kollu Elbise", 
    gender: "Kadın",
    category: "Elbise",
    subCategory: "Uzun Elbise", 
    price: 12990,
    size: ["36", "38", "40"], 
    color: ["Kahve"], 
    material: "Kumaş", 
    length: "Uzun", 
    stock: 7,
    description:
      "Yumuşak dokulu kumaşı ve zarif kesimiyle bu kahverengi elbise, günlük ve özel davetler için idealdir.",
    features: ["Yumuşak doku", "Zarif kesim", "Vakko"],
    tags: ["kadın", "elbise", "kahve", "uzun", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Klasik Gömlek",
    gender: "Erkek",
    category: "Üst Giyim", 
    subCategory: "Gömlek",
    price: 7990,
    size: ["M", "L", "XL", "XXL"], 
    color: ["Bilinmiyor"], 
    material: "Kumaş", 
    length: "Orta", 
    stock: 18,
    description:
      "Kaliteli kumaşı ve klasik kesimiyle öne çıkan bu gömlek, her ortama uyum sağlayan zamansız bir parçadır.",
    features: ["Kaliteli kumaş", "Klasik kesim", "Vakko"],
    tags: ["erkek", "gömlek", "klasik", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Gri Tişört", 
    gender: "Kadın", 
    category: "Üst Giyim", 
    subCategory: "Tişört",
    price: 3990,
    size: ["S", "M", "L"], 
    color: ["Gri"], 
    material: "Pamuklu", 
    length: "Kısa", 
    stock: 22,
    description:
      "Pamuklu kumaştan üretilmiş bu gri tişört, sade ve modern bir görünüm sunar.",
    features: ["Pamuklu kumaş", "Sade tasarım", "Vakko"],
    tags: ["kadın", "tişört", "gri", "vakko", "basic"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Yün Akrilik Palto",
    gender: "Erkek",
    category: "Dış Giyim", 
    subCategory: "Palto",
    price: 15990,
    size: ["M", "L", "XL"], 
    color: ["Bilinmiyor"], 
    material: "Yün Akrilik", 
    length: "Uzun", 
    stock: 10,
    description:
      "Soğuk günler için ideal olan bu yün karışımlı palto, klasik kesimiyle zarif bir görünüm sağlar.",
    features: ["Yün karışımlı", "Klasik kesim", "Vakko"],
    tags: ["erkek", "palto", "yün", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Pembe Kaşmir İpek Triko",
    gender: "Kadın",
    category: "Üst Giyim", 
    subCategory: "Triko",
    price: 9490,
    size: ["S", "M", "L"], 
    color: ["Pembe"], 
    material: "Kaşmir İpek", 
    length: "Orta", 
    stock: 11,
    description:
      "Kaşmir ve ipek karışımıyla üretilen bu pembe triko, hem yumuşak dokusu hem de zarif görünümüyle öne çıkar.",
    features: ["Kaşmir ipek karışımı", "Yumuşak doku", "Vakko"],
    tags: ["kadın", "triko", "pembe", "kaşmir", "ipek", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Turkuaz O Yaka Kısa Kollu T-Shirt", 
    gender: "Erkek",
    category: "Üst Giyim", 
    subCategory: "Tişört",
    price: 3690,
    size: ["M", "L", "XL"], 
    color: ["Turkuaz"], 
    material: "Pamuklu", 
    length: "Kısa", 
    stock: 17,
    description:
      "Canlı turkuaz rengiyle dikkat çeken bu tişört, yumuşak pamuklu yapısıyla konfor sağlar.",
    features: ["Yumuşak pamuklu", "Canlı renk", "Vakko"],
    tags: ["erkek", "tişört", "turkuaz", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Haki V Yaka Uzun Kollu T-Shirt",
    gender: "Kadın",
    category: "Üst Giyim", 
    subCategory: "Tişört",
    price: 4290,
    size: ["S", "M", "L"], 
    color: ["Haki"], 
    material: "Kumaş", 
    length: "Uzun", 
    stock: 16,
    description:
      "Modern kesimli bu haki tişört, V yaka detayıyla spor ve şık kombinlerde kullanılabilir.",
    features: ["V Yaka", "Modern kesim", "Vakko"],
    tags: ["kadın", "tişört", "haki", "uzun kollu", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Tek Pilili Balıksırtı Yün Pantolon",
    gender: "Erkek",
    category: "Alt Giyim",
    subCategory: "Pantolon",
    price: 17950,
    size: ["46", "48", "50", "52"],
    color: ["Camel"],
    material: "%100 Merinos Yünü",
    length: "Uzun",
    stock: 10,
    description: "Tek pilili ve balıksırtı desenli, %100 Merinos yününden üretilmiş contemporary tarzda pantolon.",
    features: ["Tek Pilili", "Balıksırtı Desen", "%100 Merinos Yünü", "Vakko"],
    tags: ["erkek", "pantolon", "yün", "balıksırtı", "camel", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Bağcıklı Ayakkabı",
    gender: "Erkek",
    category: "Ayakkabı",
    subCategory: "Klasik Ayakkabı",
    price: 39950,
    size: ["40", "41", "42", "43"],
    color: ["Kahve"],
    material: "Deri",
    length: "Orta",
    stock: 10,
    description: "Klasik kesim, bağcıklı deri erkek ayakkabısı.",
    features: ["Bağcıklı", "Deri", "Klasik Tasarım", "Vakko"],
    tags: ["erkek", "ayakkabı", "klasik", "bağcıklı", "deri", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Yün Kaşmir Palto",
    gender: "Erkek",
    category: "Dış Giyim",
    subCategory: "Palto",
    price: 14550, 
    size: ["44", "46", "48", "50", "52", "54", "56", "58"],
    color: ["Kahve"],
    material: "%93 Koyun Yünü, %7 Kaşmir",
    length: "Uzun",
    stock: 10,
    description: "Düz, contemporary tarzda, %93 koyun yünü ve %7 kaşmir karışımlı dokuma palto.",
    features: ["Yün Kaşmir Karışımı", "Dokuma", "Contemporary", "Vakko"],
    tags: ["erkek", "palto", "yün", "kaşmir", "kahve", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Exclusive Twill Gömlek",
    gender: "Erkek",
    category: "Üst Giyim",
    subCategory: "Gömlek",
    price: 10950,
    size: ["39", "40", "41", "42", "43", "44", "45"],
    color: ["Mavi", "Beyaz"],
    material: "%100 Pamuk",
    length: "Orta",
    stock: 15,
    description: "Mavi renkli Vakko Exclusive twill gömlek, düğme kapamalıdır. Comfort kesim.",
    features: ["%100 Pamuk", "Twill Dokuma", "Comfort Kesim", "Vakko"],
    tags: ["erkek", "gömlek", "pamuk", "twill", "mavi", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Kruvaze Yarım Astarlı Yün Kaşmir Ceket",
    gender: "Erkek",
    category: "Dış Giyim",
    subCategory: "Ceket",
    price: 55650, // <-- DİKKAT: Bu fiyatı manuel olarak güncellemelisin.
    size: ["44", "46", "48", "50", "52", "54", "56", "58", "60"],
    color: ["Gri"],
    material: "%93 Yeni Yün, %7 Kaşmir",
    length: "Orta",
    stock: 10,
    description: "Yeni yün, kaşmir kumaştan üretilen gri renkli Vakko By Tagliatore ceket; kruvaze yakaya ve cep detaylarına sahiptir.",
    features: ["Kruvaze", "Yarım Astarlı", "Yün Kaşmir Karışımı", "Vakko By Tagliatore"],
    tags: ["erkek", "ceket", "kruvaze", "yün", "kaşmir", "gri", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Aplike Cepli Yün Spor Ceket",
    gender: "Erkek",
    category: "Dış Giyim",
    subCategory: "Ceket",
    price: 89950,
    size: ["S", "M", "L", "XL", "XXL", "XXXL"],
    color: ["Siyah"],
    material: "%100 Koyun Yünü",
    length: "Orta",
    stock: 12,
    description: "Koyun yünü kumaştan üretilen klasik yakalı, siyah renkli Vakko ceket; göğüs cebine, etek ceplerine ve tam boy düğme kapama detayına sahiptir.",
    features: ["Aplike Cepli", "%100 Koyun Yünü", "Spor Ceket", "Vakko"],
    tags: ["erkek", "ceket", "yün", "siyah", "spor ceket", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Uzun Kollu Bisiklet Yaka Tişört",
    gender: "Erkek",
    category: "Üst Giyim",
    subCategory: "Tişört",
    price: 19900, 
    size: ["M", "L", "XL", "XXL", "XXXL"],
    color: ["Siyah", "Antrasit", "Lacivert"],
    material: "%100 Pamuk",
    length: "Uzun",
    stock: 18,
    description: "Pamuklu örme kumaşa sahip olan Vakko t-shirt, bisiklet yakalı ve uzun kolludur.",
    features: ["%100 Pamuk", "Uzun Kollu", "Bisiklet Yaka", "Vakko"],
    tags: ["erkek", "tişört", "uzun kollu", "pamuk", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Kırmızı Dar Paça Pantolon",
    gender: "Kadın",
    category: "Alt Giyim",
    subCategory: "Pantolon",
    price: 13950,
    size: ["34", "36", "38", "40", "42", "44", "46"],
    color: ["Kırmızı"],
    material: "%52 Pamuk, %45 Viskon, %3 Elastan",
    length: "Uzun",
    stock: 15,
    description: "Dar paça kesimli, canlı kırmızı renkte, pamuk ve viskon karışımlı esnek kumaşlı pantolon.",
    features: ["Dar Paça", "Pamuk Viskon Karışımı", "Esnek Kumaş", "Vakko"],
    tags: ["kadın", "pantolon", "dar paça", "kırmızı", "pamuk", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Ekru Dik Yaka Triko",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Triko",
    price: 11950,
    size: ["XS", "S", "M", "L", "XL"],
    color: ["Ekru"],
    material: "%100 Yün",
    length: "Orta",
    stock: 12,
    description: "Ekru renkli, dik yakalı, %100 yün içeriğiyle sıcak tutan şık triko.",
    features: ["Dik Yaka", "%100 Yün", "Vakko"],
    tags: ["kadın", "triko", "ekru", "dik yaka", "yün", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Haki Sweatshirt",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Sweatshirt",
    price: 14950,
    size: ["XS", "S", "M", "L", "XL"],
    color: ["Haki"],
    material: "Pamuklu",
    length: "Orta",
    stock: 15,
    description: "Yan ceplere, manşet detaylarına, tam boy fermuar kapama detayına sahip olan haki renkli Vakko sweatshirt, kapüşonlu yakası ile dikkat çekiyor.",
    features: ["Kapüşonlu Yaka", "Tam Boy Fermuar", "Yan Cepler", "Vakko"],
    tags: ["kadın", "sweatshirt", "haki", "kapüşonlu", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Vizon Manto",
    gender: "Kadın",
    category: "Dış Giyim",
    subCategory: "Manto",
    price: 85950,
    size: ["36", "38", "40", "42", "44", "46"],
    color: ["Vizon"],
    material: "%75 Alpaka, %25 Koyun Yünü",
    length: "Uzun",
    stock: 10,
    description: "Alpaka-yün karışımlı Vakko manto, kruvaze yakası, yumuşak dokusu ve vizon rengi ile öne çıkıyor.",
    features: ["Alpaka-Yün Karışımı", "Kruvaze Yaka", "Yumuşak Doku", "Vakko"],
    tags: ["kadın", "manto", "vizon", "alpaka", "yün", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Bej Kaban",
    gender: "Kadın",
    category: "Dış Giyim",
    subCategory: "Kaban",
    price: 32995,
    size: ["36", "38", "40", "42", "44"],
    color: ["Bej"],
    material: "%70 Alpaka, %30 Koyun Yünü",
    length: "Uzun",
    stock: 10,
    description: "Düğme kapamalı ve yumuşak kumaşlı kaban, bej tonu ile her stile uyum sağlıyor. %70 Alpaka, %30 Koyun Yünü.",
    features: ["%70 Alpaka", "%30 Koyun Yünü", "Düğme Kapamalı", "Vakko"],
    tags: ["kadın", "kaban", "bej", "alpaka", "yün", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Beyaz T-Shirt",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Tişört",
    price: 11165,
    size: ["XS", "S", "M", "L", "XL"],
    color: ["Beyaz"],
    material: "Pamuklu",
    length: "Kısa",
    stock: 15,
    description: "Bisiklet yakalı Vakko by Peserico t-shirt, beyaz rengi ve zincir aksesuarı ile öne çıkıyor.",
    features: ["Bisiklet Yaka", "Zincir Aksesuarlı", "Vakko by Peserico"],
    tags: ["kadın", "tişört", "beyaz", "bisiklet yaka", "vakko", "peserico"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Mavi Kaşmir Triko (Ermanno Scervino)",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Triko",
    price: 32480, 
    size: ["36", "38", "40", "42"],
    color: ["Mavi", "Pastel Mavi"],
    material: "%100 Kaşmir",
    length: "Kısa",
    stock: 12,
    description: "Bisiklet yakalı, kısa kollu pastel mavi triko, dantel detaylarıyla dikkat çekiyor.",
    features: ["Bisiklet Yaka", "Kısa Kollu", "Dantel Detaylı", "%100 Kaşmir", "Ermanno Scervino"],
    tags: ["kadın", "triko", "kaşmir", "mavi", "dantel", "vakko", "Ermanno Scervino"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Gri Kapüşonlu Sweatshirt (Vakko By Lorena Antoniazzi)",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Sweatshirt",
    price: 57950,
    size: ["34", "36", "38", "40", "42", "44"],
    color: ["Gri"],
    material: "%100 Koyun Yünü",
    length: "Orta",
    stock: 15,
    description: "Vakko By Lorena Antoniazzi sweatshirt; modal-kaşmir dokusu, gri tonu ve şerit detayları ile öne çıkıyor.",
    features: ["Modal-Kaşmir Doku", "Şerit Detaylı", "Kapüşonlu", "Vakko By Lorena Antoniazzi"],
    tags: ["kadın", "sweatshirt", "gri", "kapüşonlu", "kaşmir", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Açık Gri O Yaka Uzun Kollu T-Shirt (Vakko By Lorena Antoniazzi)",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Tişört",
    price: 26950,
    size: ["36", "38", "40", "42"],
    color: ["Açık Gri"],
    material: "%88 Viskoz, %12 İpek",
    length: "Uzun",
    stock: 15,
    description: "Açık gri renkli Vakko By Lorena Antoniazzi t-shirt, O yakalı ve uzun kolludur.",
    features: ["O Yaka", "Uzun Kollu", "Viskoz İpek Karışımı", "Vakko By Lorena Antoniazzi"],
    tags: ["kadın", "tişört", "açık gri", "uzun kollu", "viskoz", "ipek", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Gri Sweatshirt",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Sweatshirt",
    price: 17950,
    size: ["36", "38", "40", "42"],
    color: ["Gri"],
    material: "Pamuk",
    length: "Orta",
    stock: 15,
    description: "Pamuk kumaştan üretilen gri renkli Vakko sweatshirt; kapüşonlu yakaya, tam boy fermuar kapama detayına sahiptir.",
    features: ["Kapüşonlu Yaka", "Tam Boy Fermuar", "Pamuk Kumaş", "Vakko"],
    tags: ["kadın", "sweatshirt", "gri", "kapüşonlu", "pamuk", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Beyaz T-Shirt (Fabiana Filippi)",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Tişört",
    price: 19950,
    size: ["34", "36", "38", "40", "42", "44"],
    color: ["Beyaz"],
    material: "Pamuklu",
    length: "Kısa",
    stock: 15,
    description: "Beyaz renkte, Fabiana Filippi tasarımı basic tişört.",
    features: ["Fabiana Filippi"],
    tags: ["kadın", "tişört", "beyaz", "fabiana filippi", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Gri Sweatshirt (Bej Yaka Detaylı)",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Sweatshirt",
    price: 11165,
    size: ["XS", "S", "M", "L", "XL"],
    color: ["Gri", "Bej"],
    material: "Kumaş",
    length: "Orta",
    stock: 15,
    description: "Vakko sweatshirt, bağcıklı kapüşonu ve bej renk yaka detayı ile dikkat çekiyor. Gri renkli bu tasarım, fermuar kapamalıdır.",
    features: ["Bağcıklı Kapüşon", "Bej Yaka Detayı", "Fermuar Kapamalı", "Vakko"],
    tags: ["kadın", "sweatshirt", "gri", "bej", "kapüşonlu", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Camel Drapeli T-Shirt (Fabiana Filippi)",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Tişört",
    price: 18950,
    size: ["34", "36", "38", "40", "42", "44"],
    color: ["Camel"],
    material: "%95 Pamuk, %5 Elastan",
    length: "Orta",
    stock: 15,
    description: "Camel renkli, %95 pamuk ve %5 elastan içerikli, drapeli tişört. Fabiana Filippi tasarımıdır.",
    features: ["Drapeli", "Pamuk Elastan Karışımı", "Fabiana Filippi"],
    tags: ["kadın", "tişört", "camel", "drapeli", "pamuk", "fabiana filippi", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Camel Kapüşonlu Sweatshirt",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Sweatshirt",
    price: 15950,
    size: ["XS", "S", "M", "L", "XL"],
    color: ["Camel"],
    material: "%51 Polyester, %44 Viskoz, %5 Elastan",
    length: "Orta",
    stock: 15,
    description: "Camel renkli, kapüşonlu, relax kalıp sweatshirt. %51 Polyester, %44 Viskoz, %5 Elastan kumaş.",
    features: ["Kapüşonlu", "Relax Kalıp", "Loungewear", "Vakko"],
    tags: ["kadın", "sweatshirt", "kapüşonlu", "camel", "loungewear", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Gri O Yaka Kısa Kollu T-Shirt",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Tişört",
    price: 10950,
    size: ["34", "36", "38", "40", "42", "44", "46"],
    color: ["Gri"],
    material: "%95 Pamuk, %5 Elastan",
    length: "Kısa",
    stock: 15,
    description: "Gri renkli, O yaka, kısa kollu basic t-shirt. Pamuk ve elastan karışımı.",
    features: ["O Yaka", "Kısa Kollu", "Basic", "Vakko"],
    tags: ["kadın", "tişört", "gri", "o yaka", "basic", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Bej Kayık Yaka Kısa Kollu T-Shirt",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Tişört",
    price: 10950,
    size: ["34", "36", "38", "40", "42", "44", "46"],
    color: ["Bej"],
    material: "%95 Pamuk, %5 Elastan",
    length: "Kısa",
    stock: 15,
    description: "Bej renkli, kayık yakalı, kısa kollu basic t-shirt. Pamuk ve elastan karışımı.",
    features: ["Kayık Yaka", "Kısa Kollu", "Basic", "Vakko"],
    tags: ["kadın", "tişört", "bej", "kayık yaka", "basic", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Ekru Basic 3/4 Kol T-Shirt",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Tişört",
    price: 11165,
    size: ["XS", "S", "M", "L", "XL"],
    color: ["Ekru"],
    material: "%94 Pamuk, %6 Elastan",
    length: "Orta",
    stock: 15,
    description: "Ekru renkli, bisiklet (round) yaka, 3/4 kol uzunluğunda basic tişört.",
    features: ["Bisiklet Yaka", "3/4 Kol", "Basic", "Vakko"],
    tags: ["kadın", "tişört", "ekru", "3/4 kol", "basic", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Beyaz Kolsuz T-Shirt",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Tişört",
    price: 10950,
    size: ["34", "36", "38", "40", "42"],
    color: ["Beyaz"],
    material: "%95 Pamuk, %5 Elastan",
    length: "Kısa",
    stock: 15,
    description: "Beyaz renkli, kolsuz, bisiklet yaka t-shirt. Pamuk ve elastan karışımı.",
    features: ["Kolsuz", "Bisiklet Yaka", "Basic", "Vakko"],
    tags: ["kadın", "tişört", "beyaz", "kolsuz", "basic", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Antrasit V Yaka T-Shirt",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Tişört",
    price: 14950,
    size: ["36", "38", "40", "42"],
    color: ["Antrasit"],
    material: "%100 Pamuk",
    length: "Kısa",
    stock: 15,
    description: "Antrasit renkli, V yakalı, %100 pamuk t-shirt.",
    features: ["V Yaka", "%100 Pamuk", "Vakko"],
    tags: ["kadın", "tişört", "antrasit", "v yaka", "pamuk", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Ekru Kapüşonlu Sweatshirt",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Sweatshirt",
    price: 17950,
    size: ["XS", "S", "M", "L", "XL"],
    color: ["Ekru"],
    material: "%51 Polyester, %44 Viskoz, %5 Elastan",
    length: "Orta",
    stock: 15,
    description: "Ekru renkli, kapüşonlu, relax kalıp loungewear sweatshirt.",
    features: ["Kapüşonlu", "Relax Kalıp", "Loungewear", "Vakko"],
    tags: ["kadın", "sweatshirt", "ekru", "kapüşonlu", "loungewear", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Ekru T-Shirt (Fabiana Filippi)",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Tişört",
    price: 13950,
    size: ["34", "36", "38", "40", "42", "44"],
    color: ["Ekru"],
    material: "%94 Pamuk, %6 Elastan",
    length: "Kısa",
    stock: 15,
    description: "Ekru renkli, pamuk ve elastan karışımlı, basic tişört. Fabiana Filippi tasarımıdır.",
    features: ["Basic", "Pamuk Elastan Karışımı", "Fabiana Filippi"],
    tags: ["kadın", "tişört", "ekru", "basic", "fabiana filippi", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Beyaz Dik Yaka T-Shirt (Fabiana Filippi)",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Tişört",
    price: 21950,
    size: ["34", "36", "38", "40", "42", "44", "46"],
    color: ["Beyaz"],
    material: "%95 Pamuk, %5 Elastan",
    length: "Kısa",
    stock: 15,
    description: "Beyaz renkli, dik yakalı, pamuk elastan karışımlı tişört. Fabiana Filippi tasarımıdır.",
    features: ["Dik Yaka", "Pamuk Elastan Karışımı", "Fabiana Filippi"],
    tags: ["kadın", "tişört", "beyaz", "dik yaka", "fabiana filippi", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Ekru Dik Yaka Sweatshirt",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Sweatshirt",
    price: 15950,
    size: ["XS", "S", "M", "L", "XL"],
    color: ["Ekru"],
    material: "%51 Polyester, %44 Viskoz, %5 Elastan",
    length: "Orta",
    stock: 15,
    description: "Ekru renkli, dik yakalı, relax kalıp loungewear sweatshirt.",
    features: ["Dik Yaka", "Relax Kalıp", "Loungewear", "Vakko"],
    tags: ["kadın", "sweatshirt", "ekru", "dik yaka", "loungewear", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Kahve Dik Yaka Sweatshirt",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Sweatshirt",
    price: 17950,
    size: ["XS", "S", "M", "L", "XL"],
    color: ["Kahve"],
    material: "%51 Polyester, %44 Viskoz, %5 Elastan",
    length: "Orta",
    stock: 15,
    description: "Kahve renkli, dik yakalı, relax kalıp loungewear sweatshirt.",
    features: ["Dik Yaka", "Relax Kalıp", "Loungewear", "Vakko"],
    tags: ["kadın", "sweatshirt", "kahve", "dik yaka", "loungewear", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Haki Kapüşonlu Sweatshirt",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Sweatshirt",
    price: 19950,
    size: ["36", "38"],
    color: ["Haki"],
    material: "%33 Viskoz, %67 Asetat",
    length: "Orta",
    stock: 15,
    description: "Vakko sweatshirt; viskoz saten görünümlü dokusu ve ajurlu kollarıyla tasarlanmıştır.",
    features: ["Kapüşonlu", "Viskoz Saten Doku", "Ajurlu Kollar", "Vakko By She's So"],
    tags: ["kadın", "sweatshirt", "haki", "kapüşonlu", "viskoz", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Siyah T-Shirt (Kaşmir Modal)",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Tişört",
    price: 12950,
    size: ["36", "38", "40", "42"],
    color: ["Siyah"],
    material: "%10 Kaşmir, %90 Modal",
    length: "Kısa",
    stock: 15,
    description: "Elastik formda payetli O yaka detayına ve kol manşetlerine sahip olan siyah renkli Vakko t-shirt, kaşmir ve modal kumaştan üretilmiştir.",
    features: ["Payetli O Yaka", "Kaşmir Modal Karışımı", "Basic", "Vakko"],
    tags: ["kadın", "tişört", "siyah", "kaşmir", "modal", "payet", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Ekru O Yaka Kısa Kollu T-Shirt",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Tişört",
    price: 26950,
    size: ["36", "38", "40", "42"],
    color: ["Ekru", "Vizon"],
    material: "%90 Pamuk, %10 Elastan",
    length: "Kısa",
    stock: 15,
    description: "Ekru-Vizon renkli, O yaka, kısa kollu, pamuk elastan karışımlı t-shirt.",
    features: ["O Yaka", "Kısa Kollu", "Pamuk Elastan Karışımı", "Vakko By Lorena Antoniazzi"],
    tags: ["kadın", "tişört", "ekru", "vizon", "pamuk", "vakko", "Lorena Antoniazzi"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Kahve Kapüşonlu Sweatshirt",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Sweatshirt",
    price: 18795,
    size: ["36", "38", "40", "42", "44"],
    color: ["Kahve"],
    material: "%5 Elastan, %70 Viskoz, %25 Polyamid",
    length: "Orta",
    stock: 15,
    description: "Kahve rengi ve balıksırtı desenli önü ile dikkat çeken Vakko sweatshirt, kapüşonlu yakaya, tam boy fermuar kapama detayına sahiptir.",
    features: ["Kapüşonlu", "Tam Boy Fermuar", "Balıksırtı Desen", "Vakko By She's So"],
    tags: ["kadın", "sweatshirt", "kahve", "kapüşonlu", "balıksırtı", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Siyah V Yaka Kısa Kollu T-Shirt",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Tişört",
    price: 4165,
    size: ["XS", "S", "M", "L", "XL"],
    color: ["Siyah"],
    material: "Kumaş",
    length: "Kısa",
    stock: 15,
    description: "V yakalı Vakko t-shirt, siyah renktir.",
    features: ["V Yaka", "Basic", "Vakko"],
    tags: ["kadın", "tişört", "siyah", "v yaka", "basic", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Beyaz Fermuarlı Sweatshirt (Fabiana Filippi)",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Sweatshirt",
    price: 22957,
    size: ["34", "36", "38", "40", "42", "44"],
    color: ["Beyaz"],
    material: "Kumaş",
    length: "Orta",
    stock: 15,
    description: "Beyaz renkli Fabiana Filippi sweatshirt, tam boy fermuar kapamalıdır. Bu tasarım, gümüş renkte zincir detayları ile dikkat çekiyor.",
    features: ["Tam Boy Fermuar", "Gümüş Zincir Detaylı", "Fabiana Filippi"],
    tags: ["kadın", "sweatshirt", "beyaz", "fermuarlı", "zincir detaylı", "fabiana filippi", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Gri T-Shirt",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Tişört",
    price: 14950,
    size: ["34", "36", "38", "40", "42", "44"],
    color: ["Gri"],
    material: "%100 Pamuk",
    length: "Kısa",
    stock: 15,
    description: "%100 pamuk kumaştan üretilen gri renkli Vakko by Peserico t-shirt; bisiklet yakaya ve kısa kol detayına sahiptir.",
    features: ["%100 Pamuk", "Bisiklet Yaka", "Kısa Kol", "Vakko by Peserico"],
    tags: ["kadın", "tişört", "gri", "pamuk", "basic", "vakko", "peserico"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Krem O Yaka Uzun Kollu T-Shirt (Fabiana Filippi)",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Tişört",
    price: 17950,
    size: ["36", "38", "40", "42", "44"],
    color: ["Krem"],
    material: "%100 Pamuk",
    length: "Uzun",
    stock: 15,
    description: "%100 pamuk kumaşa sahip olan Vakko t-shirt, O yakalı ve uzun kolludur.",
    features: ["%100 Pamuk", "O Yaka", "Uzun Kollu", "Fabiana Filippi"],
    tags: ["kadın", "tişört", "krem", "pamuk", "uzun kollu", "fabiana filippi", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Ekru Drapeli Bluz (Fabiana Filippi)",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Bluz",
    price: 23950,
    size: ["34", "36", "38", "40", "42", "44"],
    color: ["Ekru"],
    material: "%94 Pamuk, %6 Elastan",
    length: "Orta",
    stock: 15,
    description: "Ekru renkli, %94 pamuk ve %6 elastan içerikli, drapeli bluz. Fabiana Filippi tasarımıdır.",
    features: ["Drapeli", "Pamuk Elastan Karışımı", "Fabiana Filippi"],
    tags: ["kadın", "bluz", "ekru", "drapeli", "pamuk", "fabiana filippi", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Beyaz Yakası Dantelli Gömlek (Fabiana Filippi)",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Gömlek",
    price: 24950,
    size: ["34", "36", "38", "40", "42", "44", "46"],
    color: ["Beyaz"],
    material: "%94 Pamuk, %6 Elastan",
    length: "Orta",
    stock: 15,
    description: "Beyaz renkli, yakası dantelli, pamuk elastan karışımlı gömlek.",
    features: ["Yakası Dantelli", "Pamuk Elastan Karışımı", "Fabiana Filippi"],
    tags: ["kadın", "gömlek", "beyaz", "dantelli", "fabiana filippi", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Bej Bluz (Ermanno Scervino)",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Bluz",
    price: 28950,
    size: ["36", "38", "40", "42"],
    color: ["Bej"],
    material: "%75 Pamuk, %25 İpek",
    length: "Orta",
    stock: 15,
    description: "Bej renkli, pamuk ipek karışımlı, fırfır detaylı bluz.",
    features: ["Fırfır Detaylı", "Pamuk İpek Karışımı", "Ermanno Scervino"],
    tags: ["kadın", "bluz", "bej", "pamuk", "ipek", "fırfırlı", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Gri İpek Bluz (Ermanno Scervino)",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Bluz",
    price: 32950,
    size: ["36", "38", "40", "42"],
    color: ["Gri"],
    material: "%100 İpek",
    length: "Orta",
    stock: 15,
    description: "Gri renkli, %100 ipek, fırfır detaylı bluz.",
    features: ["%100 İpek", "Fırfır Detaylı", "Ermanno Scervino"],
    tags: ["kadın", "bluz", "gri", "ipek", "fırfırlı", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Bej Kapüşonlu Uzun Kollu Bluz",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Bluz",
    price: 17950,
    size: ["34", "36", "38", "40", "42", "44", "46"],
    color: ["Bej"],
    material: "%51 Polyester, %44 Viskoz, %5 Elastan",
    length: "Uzun",
    stock: 15,
    description: "Bej renkli, kapüşonlu yaka, uzun kollu, relax kalıp loungewear bluz.",
    features: ["Kapüşonlu Yaka", "Relax Kalıp", "Loungewear", "Vakko"],
    tags: ["kadın", "bluz", "bej", "kapüşonlu", "loungewear", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Haki Uzun Kollu Gömlek (P.A.R.O.S.H.)",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Gömlek",
    price: 14950,
    size: ["34", "36", "38", "40", "42", "44"],
    color: ["Haki"],
    material: "%100 Pamuk",
    length: "Uzun",
    stock: 15,
    description: "Haki renkli, %100 pamuklu, klasik yaka, uzun kollu gömlek.",
    features: ["%100 Pamuk", "Klasik Yaka", "P.A.R.O.S.H."],
    tags: ["kadın", "gömlek", "haki", "pamuk", "uzun kollu", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Kırmızı Uzun Kollu Gömlek (P.A.R.O.S.H.)",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Gömlek",
    price: 22950,
    size: ["36", "38", "40", "42"],
    color: ["Kırmızı"],
    material: "%100 İpek",
    length: "Uzun",
    stock: 15,
    description: "Kırmızı renkli, %100 ipek, klasik yaka, uzun kollu gömlek.",
    features: ["%100 İpek", "Klasik Yaka", "P.A.R.O.S.H."],
    tags: ["kadın", "gömlek", "kırmızı", "ipek", "uzun kollu", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Mavi Uzun Kollu Gömlek",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Gömlek",
    price: 12950,
    size: ["36", "38", "40"],
    color: ["Mavi"],
    material: "%100 Pamuk",
    length: "Uzun",
    stock: 15,
    description: "Mavi renkli, %100 pamuklu, klasik yaka, uzun kollu gömlek.",
    features: ["%100 Pamuk", "Klasik Yaka", "Vakko By She's So"],
    tags: ["kadın", "gömlek", "mavi", "pamuk", "uzun kollu", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Çok Renkli Uzun Kollu Gömlek",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Gömlek",
    price: 1595,
    size: ["36", "38", "40", "42", "44"],
    color: ["Çok Renkli"],
    material: "%100 İpek",
    length: "Uzun",
    stock: 15,
    description: "Çok renkli, %100 ipek, desenli, klasik yaka, uzun kollu gömlek.",
    features: ["%100 İpek", "Desenli", "Klasik Yaka", "Vakko"],
    tags: ["kadın", "gömlek", "çok renkli", "ipek", "desenli", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Açık Gri Dar Kesim Bluz",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Bluz",
    price: 17950,
    size: ["36", "38", "40", "42"],
    color: ["Açık Gri"],
    material: "%47 Viskoz, %50 Polyamid, %3 Elastan",
    length: "Orta",
    stock: 15,
    description: "Açık gri renkli, dar kesim, viskoz ve polyamid karışımlı bluz.",
    features: ["Dar Kesim", "Viskoz Karışımı", "Vakko By She's So"],
    tags: ["kadın", "bluz", "açık gri", "dar kesim", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Açık Gri-Kahve Bluz)",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Bluz",
    price: 19950,
    size: ["36", "38", "40", "42"],
    color: ["Açık Gri", "Kahve"],
    material: "%95 Viskoz, %5 Elastan",
    length: "Orta",
    stock: 15,
    description: "Açık gri ve kahve tonlarında, viskoz elastan karışımlı, desenli bluz.",
    features: ["Desenli", "Viskoz Karışımı", "Vakko By She's So"],
    tags: ["kadın", "bluz", "açık gri", "kahve", "desenli", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Kahve İpek Bluz",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Bluz",
    price: 17950,
    size: ["36", "38", "40", "42", "44", "46"],
    color: ["Kahve"],
    material: "%100 İpek",
    length: "Orta",
    stock: 15,
    description: "Kahve renkli, %100 ipek kumaştan üretilmiş, klasik yaka bluz.",
    features: ["%100 İpek", "Klasik Yaka", "Vakko"],
    tags: ["kadın", "bluz", "kahve", "ipek", "klasik", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Siyah Örgülü Bluz (Ermanno Scervino)",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Bluz",
    price: 49950,
    size: ["36", "38", "40", "42"],
    color: ["Siyah"],
    material: "%94 Pamuk, %6 Elastan",
    length: "Orta",
    stock: 15,
    description: "Siyah renkli, pamuk elastan karışımlı, örgülü bluz.",
    features: ["Örgülü", "Pamuk Karışımı", "Ermanno Scervino"],
    tags: ["kadın", "bluz", "siyah", "örgülü", "pamuk", "vakko", "Ermanno Scervino"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Lacivert Gömlek (Ermanno Scervino)",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Gömlek",
    price: 24950,
    size: ["36", "38", "40", "42"],
    color: ["Lacivert"],
    material: "%100 Pamuk",
    length: "Orta",
    stock: 15,
    description: "Lacivert renkli, %100 pamuklu, klasik yaka gömlek.",
    features: ["%100 Pamuk", "Klasik Yaka", "Ermanno Scervino"],
    tags: ["kadın", "gömlek", "lacivert", "pamuk", "vakko", "Ermanno Scervino"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Pembe Triko",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Triko",
    price: 12950,
    size: ["S", "M", "L"],
    color: ["Pembe"],
    material: "%100 Kaşmir",
    length: "Orta",
    stock: 15,
    description: "Pembe renkli, %100 kaşmir, bisiklet yaka triko.",
    features: ["%100 Kaşmir", "Bisiklet Yaka", "Vakko"],
    tags: ["kadın", "triko", "pembe", "kaşmir", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Mint Kaşmir Triko (Ermanno Scervino)",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Triko",
    price: 47950,
    size: ["36", "38", "40", "42"],
    color: ["Mint"],
    material: "%100 Kaşmir",
    length: "Orta",
    stock: 15,
    description: "Mint yeşili, %100 kaşmir, V yaka triko.",
    features: ["%100 Kaşmir", "V Yaka", "Ermanno Scervino"],
    tags: ["kadın", "triko", "mint", "kaşmir", "v yaka", "vakko", "Ermanno Scervino"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Ekru Payetli Triko",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Triko",
    price: 24950,
    size: ["34", "36", "38", "40", "42", "44"],
    color: ["Ekru"],
    material: "%70 Yün, %20 İpek, %10 Kaşmir",
    length: "Orta",
    stock: 15,
    description: "Ekru renkli, yün, ipek ve kaşmir karışımlı, payet detaylı triko.",
    features: ["Payet Detaylı", "Yün İpek Kaşmir Karışımı", "Vakko by Peserico"],
    tags: ["kadın", "triko", "ekru", "payet", "yün", "ipek", "kaşmir", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Ekru-Bej Yün Triko",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Triko",
    price: 30765,
    size: ["36", "38"],
    color: ["Ekru", "Bej"],
    material: "%100 Koyun Yünü",
    length: "Orta",
    stock: 15,
    description: "Ekru, bej renkli Vakko By Lorena Antoniazzi triko, yeni yün karışımlı kumaştan üretilmiştir. Bu tasarım, geniş formda dik yaka tasarımı ile dikkat çekiyor.",
    features: ["Dik Yaka", "Geniş Form", "%100 Koyun Yünü", "Vakko By Lorena Antoniazzi"],
    tags: ["kadın", "triko", "ekru", "bej", "yün", "dik yaka", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Ekru Triko (Dore Baklava Desenli)",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Triko",
    price: 17950,
    size: ["S", "M"],
    color: ["Ekru", "Dore"],
    material: "%37 Koyun Yünü, %32 Alpaka, %26 Polyamid, %5 Polyester",
    length: "Orta",
    stock: 15,
    description: "Ekru renkli Vakko triko; dore renkte baklava deseni, O yaka detayı ve alpaka-yün karışımı kumaşı ile dikkat çekiyor.",
    features: ["Baklava Desenli", "O Yaka", "Alpaka Yün Karışımı", "Vakko"],
    tags: ["kadın", "triko", "ekru", "dore", "baklava desenli", "alpaka", "yün", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Pudra Triko (V Yaka)",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Triko",
    price: 11165,
    size: ["XS", "S", "M", "L", "XL"],
    color: ["Pudra", "Ekru"],
    material: "Pamuk karışımlı",
    length: "Orta",
    stock: 15,
    description: "Pamuk karışımlı kumaştan üretilen pudra, ekru renkli Vakko triko; V yakalıdır. Tam boy düğme kapamalı bu model, etek ceplerine sahiptir.",
    features: ["V Yakalı", "Tam Boy Düğme Kapamalı", "Etek Cepleri", "Pamuk Karışımlı", "Vakko"],
    tags: ["kadın", "triko", "pudra", "ekru", "v yaka", "pamuk", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Bej O Yaka Triko (Fabiana Filippi)",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Triko",
    price: 39950,
    size: ["34", "36", "38", "40", "42", "44"],
    color: ["Bej"],
    material: "%15 İpek, %75 Yeni Yün, %10 Kaşmir",
    length: "Orta",
    stock: 15,
    description: "Yün, ipek ve kaşmir karışımlı Fabiana Filippi triko, taş işlemeli yakasıyla dikkat çekici bir stil sağlıyor.",
    features: ["Taş İşlemeli Yaka", "Yün İpek Kaşmir Karışımı", "Fabiana Filippi"],
    tags: ["kadın", "triko", "bej", "yün", "ipek", "kaşmir", "fabiana filippi", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Haki Kaşmir/İpek Triko (Vakko By Peserico)",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Triko",
    price: 29950,
    size: ["S", "M", "L", "XL"],
    color: ["Haki"],
    material: "%30 İpek, %70 Kaşmir",
    length: "Orta",
    stock: 15,
    description: "Haki renkte tasarlanan Vakko By Peserico triko, kaşmir ve ipek karışımlı kumaşı, balıkçı yaka formu ve zincir şerit detayıyla zarif bir stil sunuyor.",
    features: ["Balıkçı Yaka", "Zincir Şerit Detaylı", "Kaşmir İpek Karışımı", "Vakko By Peserico"],
    tags: ["kadın", "triko", "haki", "kaşmir", "ipek", "balıkçı yaka", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Haki V Yaka Triko",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Triko",
    price: 9950,
    size: ["S", "M", "L", "XL"],
    color: ["Haki"],
    material: "%73 Viskoz, %22 Polyamid, %5 Kaşmir",
    length: "Orta",
    stock: 15,
    description: "Haki renkli, V yaka, viskoz ve kaşmir karışımlı, standart kalıp triko.",
    features: ["V Yaka", "Viskoz Kaşmir Karışımı", "Basic", "Vakko"],
    tags: ["kadın", "triko", "haki", "v yaka", "viskoz", "kaşmir", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Bej Dik Yaka Triko (Fabiana Filippi)",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Triko",
    price: 19950,
    size: ["34", "36", "38", "40", "42"],
    color: ["Bej"],
    material: "%23 Polyester, %77 Viskoz",
    length: "Orta",
    stock: 15,
    description: "Bej renkli Fabiana Filippi triko, dik yakalıdır. Bu tasarım, çizgili desenleri ve füme renkte simli bilek kısmı ile dikkat çekiyor.",
    features: ["Dik Yaka", "Çizgili Desenli", "Simli Bilek", "Fabiana Filippi"],
    tags: ["kadın", "triko", "bej", "dik yaka", "çizgili", "viskoz", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Bej Triko (Gümüş Renkli)",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Triko",
    price: 19950,
    size: ["S", "M", "L", "XL"],
    color: ["Bej", "Gümüş"],
    material: "%42 Viskoz, %21 Koyun Yünü, %18 Polyamid, %11 İpek, %8 Polyester",
    length: "Orta",
    stock: 15,
    description: "İpek, koyun yünü karışımlı kumaştan üretilen Vakko triko kazak, bej ve gümüş renktir.",
    features: ["İpek Yün Karışımı", "Gümüş Detaylı", "Vakko"],
    tags: ["kadın", "triko", "bej", "gümüş", "ipek", "yün", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Siyah-Beyaz Triko",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Triko",
    price: 13965, 
    size: ["S", "M"], 
    color: ["Siyah", "Beyaz"],
    material: "%20 Polyamid, %80 Moher",
    length: "Orta",
    stock: 10,
    description: "Siyah-beyaz, moher karışımlı, casual triko.",
    features: ["Moher Karışımlı", "Casual", "Vakko"],
    tags: ["kadın", "triko", "siyah", "beyaz", "moher", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Koyu Kırmızı Triko",
    gender: "Kadın",
    category: "Üst Giyim",
    subCategory: "Triko",
    price: 8950, 
    size: ["S", "M", "L"], 
    color: ["Koyu Kırmızı"],
    material: "%27 Polyester, %50 Viskoz, %23 Polyamid",
    length: "Orta",
    stock: 10,
    description: "Koyu kırmızı, viskoz karışımlı, düz, standart kalıp triko.",
    features: ["Standart Kalıp", "Viskoz Karışımı", "Vakko"],
    tags: ["kadın", "triko", "kırmızı", "düz", "viskoz", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Gri Çizgili Bol Paça Pantolon (Vakko By Peserico)",
    gender: "Kadın",
    category: "Alt Giyim",
    subCategory: "Pantolon",
    price: 15177,
    size: ["34", "36", "38", "40", "42"],
    color: ["Gri", "Bej"],
    material: "İpek, Yeni Yün",
    length: "Uzun",
    stock: 15,
    description: "İpek, yeni yün kumaştan üretilen Vakko bol paça pantolon, gri ve bej renk çizgili deseni ile dikkat çekiyor.",
    features: ["Bol Paça", "Çizgili Desen", "İpek Yün Karışımı", "Vakko By Peserico"],
    tags: ["kadın", "pantolon", "gri", "bol paça", "çizgili", "ipek", "yün", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Bej Desenli Pantolon",
    gender: "Kadın",
    category: "Alt Giyim",
    subCategory: "Pantolon",
    price: 42950, 
    size: ["34", "36", "38", "40", "42", "44"], 
    color: ["Bej"],
    material: "Kumaş",
    length: "Uzun",
    stock: 10,
    description: "Bej renkli, desenli Vakko pantolon.",
    features: ["Desenli", "Vakko"],
    tags: ["kadın", "pantolon", "bej", "desenli", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Açık Gri Dar Paça Spor Pantolon",
    gender: "Kadın",
    category: "Alt Giyim",
    subCategory: "Pantolon",
    price: 37950, 
    size: ["34", "36", "38", "40", "42", "44"], 
    color: ["Açık Gri"],
    material: "Spor Kumaş",
    length: "Uzun",
    stock: 10,
    description: "Açık gri renkli, dar paça kesimli spor pantolon.",
    features: ["Dar Paça", "Spor Kesim", "Vakko"],
    tags: ["kadın", "pantolon", "açık gri", "dar paça", "spor", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Vizon Bol Kesim Pantolon",
    gender: "Kadın",
    category: "Alt Giyim",
    subCategory: "Pantolon",
    price: 16065,
    size: ["36", "38", "40", "42"],
    color: ["Vizon"],
    material: "%64 Polyester, %33 Viskoz, %3 Elastan",
    length: "Uzun",
    stock: 15,
    description: "Yan ve arka ceplere sahip, vizon renkli, bol kesim pantolon. Yanlarda siyah renk şerit detayı bulunur.",
    features: ["Bol Kesim", "Siyah Şerit Detaylı", "Polyester Viskoz Karışımı", "Vakko"],
    tags: ["kadın", "pantolon", "vizon", "bol kesim", "şeritli", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Kahve Bol Paça Pantolon (Vakko By Peserico)",
    gender: "Kadın",
    category: "Alt Giyim",
    subCategory: "Pantolon",
    price: 25950, 
    size: ["34", "36", "38", "40", "42", "44", "46"],
    color: ["Kahve", "Bej"],
    material: "%98 Yeni Yün, %1 Elastan, %1 Polyamid",
    length: "Uzun",
    stock: 15,
    description: "Kahve-Bej renkli, yeni yün kumaştan üretilmiş bol paça pantolon.",
    features: ["Bol Paça", "Yeni Yün", "Vakko By Peserico"],
    tags: ["kadın", "pantolon", "kahve", "bol paça", "yün", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Ekru Pantolon",
    gender: "Kadın",
    category: "Alt Giyim",
    subCategory: "Pantolon",
    price: 13395, 
    size: ["34", "36", "38", "40", "42", "44"], 
    color: ["Ekru"],
    material: "Kumaş",
    length: "Uzun",
    stock: 10,
    description: "Ekru renkli Vakko pantolon.",
    features: ["Vakko"],
    tags: ["kadın", "pantolon", "ekru", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Bej-Siyah Ekose Pantolon (Vakko By Pe De Chumbo)",
    gender: "Kadın",
    category: "Alt Giyim",
    subCategory: "Pantolon",
    price: 32950,
    size: ["S", "M", "L"],
    color: ["Bej", "Siyah"],
    material: "%40 Polyester, %30 Viskoz, %20 Pamuk, %5 Elastan",
    length: "Uzun",
    stock: 15,
    description: "Siyah ve bej renkli, ekose desenli, bol paçalı pantolon. Pamuk karışımlı kumaştan üretilmiştir.",
    features: ["Ekose Desen", "Bol Paça", "Vakko By Pe De Chumbo"],
    tags: ["kadın", "pantolon", "bej", "siyah", "ekose", "bol paça", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Siyah Pantolon (Fabiana Filippi)",
    gender: "Kadın",
    category: "Alt Giyim",
    subCategory: "Pantolon",
    price: 42950,
    size: ["34", "36", "38", "40", "42"],
    color: ["Siyah"],
    material: "%50 Viskoz, %50 Asetat",
    length: "Uzun",
    stock: 15,
    description: "Siyah renkli, viskoz ve asetat karışımlı, dokuma kumaş pantolon. Fabiana Filippi tasarımıdır.",
    features: ["Siyah", "Viskoz Asetat Karışımı", "Fabiana Filippi"],
    tags: ["kadın", "pantolon", "siyah", "fabiana filippi", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Siyah Pantolon (Fabiana Filippi)",
    gender: "Kadın",
    category: "Alt Giyim",
    subCategory: "Pantolon",
    price: 42950,
    size: ["34", "36", "38", "40", "42"],
    color: ["Siyah"],
    material: "%50 Viskoz, %50 Asetat",
    length: "Uzun",
    stock: 15,
    description: "Siyah renkli, viskoz ve asetat karışımlı, dokuma kumaş pantolon. Fabiana Filippi tasarımıdır.",
    features: ["Siyah", "Viskoz Asetat Karışımı", "Fabiana Filippi"],
    tags: ["kadın", "pantolon", "siyah", "fabiana filippi", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Gri Pantolon (Fabiana Filippi)",
    gender: "Kadın",
    category: "Alt Giyim",
    subCategory: "Pantolon",
    price: 30950,
    size: ["34", "36", "38", "40", "42"],
    color: ["Gri"],
    material: "%75 Yeni Yün, %23 Polyamid, %2 Elastan",
    length: "Uzun",
    stock: 15,
    description: "Gri renkli Fabiana Filippi pantolon, yan ceplere ve elastik bel bandına sahiptir. Gümüş zincir detayı ile öne çıkar.",
    features: ["Zincir Detaylı", "Elastik Bel", "Yeni Yün Karışımı", "Fabiana Filippi"],
    tags: ["kadın", "pantolon", "gri", "yün", "zincir", "fabiana filippi", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Haki Bol Paça Spor Pantolon",
    gender: "Kadın",
    category: "Alt Giyim",
    subCategory: "Pantolon",
    price: 19950,
    size: ["36", "38", "40", "42"],
    color: ["Haki"],
    material: "Spor Kumaş",
    length: "Uzun",
    stock: 15,
    description: "Haki renkli, bol paça kesimli, rahat kullanımlı spor pantolon.",
    features: ["Bol Paça", "Spor Kesim", "Vakko"],
    tags: ["kadın", "pantolon", "haki", "bol paça", "spor", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Haki Boru Paça Pantolon (Fabiana Filippi)",
    gender: "Kadın",
    category: "Alt Giyim",
    subCategory: "Pantolon",
    price: 23595,
    size: ["34", "36", "38", "40", "42", "44", "46"],
    color: ["Haki"],
    material: "%75 Yeni Yün, %23 Polyamid, %2 Elastan",
    length: "Uzun",
    stock: 15,
    description: "Haki renkli Fabiana Filippi pantolon, yeni yün karışımlı kumaştan üretilmiştir. Elastik bel bandına sahip olan bu boru paçalı tasarım, zincir aksesuarı ile dikkat çekiyor.",
    features: ["Boru Paça", "Zincir Aksesuar", "Yeni Yün Karışımı", "Fabiana Filippi"],
    tags: ["kadın", "pantolon", "haki", "boru paça", "yün", "fabiana filippi", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Haki Parlak Pantolon (Vakko By Peserico)",
    gender: "Kadın",
    category: "Alt Giyim",
    subCategory: "Pantolon",
    price: 22950, 
    size: ["34", "36", "38", "40", "42", "44", "46"],
    color: ["Haki"],
    material: "%100 Viskoz",
    length: "Uzun",
    stock: 15,
    description: "Haki renkli, viskoz dokuma, parlak görünümlü Vakko By Peserico pantolon. Lastikli bel ve duble paça detaylı.",
    features: ["Parlak Görünüm", "Lastikli Bel", "Duble Paça", "Vakko By Peserico"],
    tags: ["kadın", "pantolon", "haki", "parlak", "viskoz", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Mavi Bol Paça Jean Pantolon (Jacob Cohen)",
    gender: "Kadın",
    category: "Alt Giyim",
    subCategory: "Jean",
    price: 20950,
    size: ["34", "36", "38", "40"],
    color: ["Mavi"],
    material: "Pamuklu Denim",
    length: "Uzun",
    stock: 15,
    description: "Mavi renkli Jacob Cohen jean pantolon, yan ve arka ceplere sahiptir. Bol paça kesimlidir.",
    features: ["Bol Paça", "Jean", "Jacob Cohen"],
    tags: ["kadın", "pantolon", "jean", "mavi", "bol paça", "jacob cohen", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Mavi Pantolon",
    gender: "Kadın",
    category: "Alt Giyim",
    subCategory: "Pantolon",
    price: 11165, 
    size: ["36", "38", "40"],
    color: ["Mavi"],
    material: "Kumaş",
    length: "Uzun",
    stock: 10,
    description: "Mavi renkli Vakko pantolon.",
    features: ["Vakko"],
    tags: ["kadın", "pantolon", "mavi", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Gri Kemerli Pantolon",
    gender: "Kadın",
    category: "Alt Giyim",
    subCategory: "Pantolon",
    price: 12565, 
    size: ["34", "36", "38", "40", "42", "44", "46"],
    color: ["Gri"],
    material: "%75 Koyun Yünü, %18 Viskoz, %3 Polyamid",
    length: "Uzun",
    stock: 15,
    description: "Yan ve arka ceplere, kemerli yüksek bel detayına sahip gri renkli Vakko pantolon. Koyun yünü karışımlı kumaş.",
    features: ["Kemerli", "Yüksek Bel", "Koyun Yünü Karışımı", "Vakko"],
    tags: ["kadın", "pantolon", "gri", "kemerli", "yün", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Kahve Dar Paça Pantolon",
    gender: "Kadın",
    category: "Alt Giyim",
    subCategory: "Pantolon",
    price: 17950, 
    size: ["34", "36", "38", "40", "42", "44", "46"],
    color: ["Kahve"],
    material: "%86 Yeni Yün, %10 Polyamid, %4 Elastan",
    length: "Uzun",
    stock: 15,
    description: "Kahve renkli Vakko pantolon, yeni yün karışımlı kumaştan üretilmiştir. Dar paçalı ve bağcıklı elastik bel bandına sahiptir.",
    features: ["Dar Paça", "Bağcıklı Bel", "Yeni Yün Karışımı", "Vakko"],
    tags: ["kadın", "pantolon", "kahve", "dar paça", "yün", "vakko"],
    createdAt: new Date(),
    updatedAt: new Date(),
  }
];

const importData = async () => {
  try {
    await connectDB();
    await Product.deleteMany();
    console.log("🗑️ Eski ürünler silindi.");

    await Product.insertMany(products);
    console.log(
      `✅ Toplam ${products.length} adet ürün (10 eski + 16 yeni) başarıyla eklendi!`
    );
    process.exit();
  } catch (error) {
    console.error("❌ Veri ekleme hatası:", error);
    process.exit(1);
  }
};

importData();